### ISSUE TITLE
Too many new connexions created with high load

### ISSUE THREAD

**Issue by erebe** [criteo/graphite-remote-adapter#23]
Version used: v0.0.9 but issue still exist in v0.0.11
Command line arguments: `-carbon-transport=tcp -write-timeout=5s -read-timeout=5s`

Hello,
I started seeing a lot of timeouts errors with load increase on graphite-remote adapter
```
err="dial tcp: lookup graphite-relay.xxx on xx.xx.xx.xx:53: dial udp xx.xx.xx.xx:53: i/o timeout" num_samples=100 source="main.go:346"
err="dial tcp xx.xx.xx.xx:3341: i/o timeout" num_samples=100 source="main.go:346"
err="dial tcp xx.xx.xx.xx:3341: context deadline exceeded"
```

after doing a `perf trace -p pid_of_adapter` I noticed a lot of number of `connect` syscall.
Doing a `perf trace -e 'connect' -p pid_of_adapter 2>&1 | grep '= 0'` reveal that there is a huge number of new connections created (I got over 500 for 10seconds of tracing)

Doing a `perf record -g -F 999 -p pid` and after a `perf report -g callee --symbol-filter=connect` we can find that `github.com/criteo/graphite-remote-adapter/graphite.(*Client).Write` is asking for those new connections.

After checking the code https://github.com/criteo/graphite-remote-adapter/blob/v0.0.9/graphite/client.go#L113 it seems indeed that each call to the write function will request to open a new connection (dns resolution + establishing tcp conx) toward graphite creating congestion during high load.

Increasing the -write-timeout argument from 5s to 30s solve the issue of lot of error messages, but this is only a partial solution as we still create a lot of new connections/dns requests.

### What is expected: 
graphite-remote-adapter should keep its existing tcp connection in order to reuse it and avoid putting pressure on the system by creating that many new connections.

**Comment by iksaif** [comment]
We need to either:
* Document that fact that people need to increase the batch size
* Make sure we keep the connection for longer period of time

Current workaround: use UDP

**Comment by erebe** [comment]
`Current workaround: use UDP`
You still need to dns resolution even with UDP, so it will not solve timeouts on `err="dial tcp: lookup graphite-relay.xxx ...`

**Comment by iksaif** [comment]
... and increase batch sizes.

This will get fixed this week
