### ISSUE TITLE
 message too long

### ISSUE THREAD

**Issue by AvihayTsayeg** [criteo/graphite-remote-adapter#38]
Hi,
I'm using prometheus operator and I'm trying to send metrics to graphite (hosted graphite).
I'm getting this error when trying to send data through the adapter.

level=warn ts=2018-05-15T13:03:59.344288008Z caller=main.go:446 num_samples=100 storage=graphite err="write udp {reporterIP}:42909->{carbonIP}:2003: write: message too long" msg="Error sending samples to remote storage"

this is my config
 --graphite.write.carbon-address=${GRAPHITE_ADDRESS} 
  --write.timeout=60s 
  --graphite.default-prefix=${GRAPHITE_PREFIX}
  --graphite.write.carbon-transport=udp

any idea how to resolve this ?

**Comment by iksaif** [comment]
That's indeed a bug, `--graphite.write.carbon-transport=tcp` will make it better.

@Thib17  looks like we are batching too many metrics in the same udp datagram
